"""initial schema

Revision ID: cc39f78f2386
Revises: 
Create Date: 2026-03-28 20:02:49.812987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc39f78f2386'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_sessions',
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('place_name', sa.Text(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capture_sessions'))
    )
    op.create_table('privacy_zones',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=False),
    sa.Column('gps_lng', sa.Float(), nullable=False),
    sa.Column('radius_metres', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_zones'))
    )
    op.create_table('memories',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('image_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('synced', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('noise_level', sa.String(length=20), nullable=True),
    sa.Column('source_device', sa.String(length=100), nullable=True),
    sa.Column('capture_trigger', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['capture_sessions.id'], name=op.f('fk_memories_session_id_capture_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_created_at'), 'memories', ['created_at'], unique=False)
    op.create_table('processing_queue',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('payload_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_attempted', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['capture_sessions.id'], name=op.f('fk_processing_queue_session_id_capture_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_queue'))
    )
    op.create_index('ix_queue_status', 'processing_queue', ['status'], unique=False)
    op.create_table('entities',
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('resolved_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_entities_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index('ix_entities_memory_id', 'entities', ['memory_id'], unique=False)
    op.create_index('ix_entities_type_value', 'entities', ['type', 'value'], unique=False)
    op.create_table('notifications',
    sa.Column('memory_id', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_notifications_memory_id_memories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('entity_relationships',
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_entity_relationships_memory_id_memories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_entity_relationships_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_entity_relationships_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relationships'))
    )
    op.create_index('ix_entity_rel_memory', 'entity_relationships', ['memory_id'], unique=False)
    op.create_index('ix_entity_rel_source', 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_entity_rel_target', 'entity_relationships', ['target_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_rel_target', table_name='entity_relationships')
    op.drop_index('ix_entity_rel_source', table_name='entity_relationships')
    op.drop_index('ix_entity_rel_memory', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_table('notifications')
    op.drop_index('ix_entities_type_value', table_name='entities')
    op.drop_index('ix_entities_memory_id', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_queue_status', table_name='processing_queue')
    op.drop_table('processing_queue')
    op.drop_index(op.f('ix_memories_created_at'), table_name='memories')
    op.drop_table('memories')
    op.drop_table('privacy_zones')
    op.drop_table('capture_sessions')
    # ### end Alembic commands ###
